app = "fly-echo-web"
primary_region = "arn"
kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
internal_port = 3000
processes = [ "app" ]
protocol = "tcp"
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 1
script_checks = [ ]

  # [services.concurrency]
  # hard_limit = 120
  # soft_limit = 100
  # type = "requests"

  [[services.ports]]
  handlers = [ "http" ]
  port = 80
  force_https = true

  [[services.ports]]
  handlers = [ "tls", "http" ]
  port = 443

[[vm]]
  size = "shared-cpu-4x"
