basePath: /
definitions:
  adapters_http_routes_api.GroupedRegistration:
    properties:
      max:
        type: integer
      registered:
        type: integer
      waiting:
        type: integer
    type: object
  adapters_http_routes_api.HealthCheckResponse:
    properties:
      status:
        type: string
    type: object
  uno_domain_model.Happening:
    properties:
      date:
        type: string
      id:
        type: string
      registrationEnd:
        type: string
      registrationGroups:
        items:
          type: integer
        type: array
      registrationStart:
        type: string
      registrationStartGroups:
        type: string
      slug:
        type: string
      title:
        type: string
      type:
        type: string
    type: object
  uno_domain_model.Question:
    properties:
      happeningID:
        type: string
      id:
        type: string
      isSensitive:
        type: boolean
      options:
        items:
          type: integer
        type: array
      required:
        type: boolean
      title:
        type: string
      type:
        type: string
    type: object
  uno_domain_model.Registration:
    properties:
      changedAt:
        type: string
      changedBy:
        type: string
      createdAt:
        type: string
      happeningID:
        type: string
      prevStatus:
        type: string
      status:
        $ref: '#/definitions/uno_domain_model.RegistrationStatus'
      unregisterReason:
        type: string
      userID:
        type: string
    type: object
  uno_domain_model.RegistrationStatus:
    enum:
    - registered
    - waiting
    - unregistered
    - pending
    - removed
    type: string
    x-enum-varnames:
    - RegistrationStatusRegistered
    - RegistrationStatusWaitlisted
    - RegistrationStatusUnregistered
    - RegistrationStatusPending
    - RegistrationStatusRemoved
  uno_domain_model.SpotRange:
    properties:
      happeningID:
        type: string
      id:
        type: string
      maxYear:
        type: integer
      minYear:
        type: integer
      spots:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: webkom@echo.uib.no
    name: echo Webkom
  description: HTTP REST API for echo Webkom Uno backend
  title: Uno API
  version: "1.0"
paths:
  /:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/adapters_http_routes_api.HealthCheckResponse'
      summary: Get health status
      tags:
      - health
  /happenings:
    get:
      description: Retrives a list of all happenings and returns them in a JSON array.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/uno_domain_model.Happening'
            type: array
      summary: Get all happenings
      tags:
      - happenings
  /happenings/{id}:
    get:
      description: Retrieves a specific happening by its unique identifier.
      parameters:
      - description: Happening ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/uno_domain_model.Happening'
        "400":
          description: Bad Request
          schema:
            type: type
        "404":
          description: Not Found
          schema:
            type: type
      summary: Get happening by ID
      tags:
      - happenings
  /happenings/{id}/questions:
    get:
      description: Retrieves all questions for a specific happening.
      parameters:
      - description: Happening ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/uno_domain_model.Question'
            type: array
        "400":
          description: Bad Request
          schema:
            type: type
        "404":
          description: Not Found
          schema:
            type: type
      summary: Get happening questions
      tags:
      - happenings
  /happenings/{id}/registrations:
    get:
      description: Retrieves all registrations for a specific happening.
      parameters:
      - description: Happening ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/uno_domain_model.Registration'
            type: array
        "400":
          description: Bad Request
          schema:
            type: type
        "404":
          description: Not Found
          schema:
            type: type
      summary: Get happening registrations
      tags:
      - happenings
  /happenings/{id}/registrations/count:
    get:
      description: Retrieves the count of registrations for a specific happening.
      parameters:
      - description: Happening ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/adapters_http_routes_api.GroupedRegistration'
        "400":
          description: Bad Request
          schema:
            type: type
        "404":
          description: Not Found
          schema:
            type: type
      summary: Get happening registrations count
      tags:
      - happenings
  /happenings/{id}/spot-ranges:
    get:
      description: Retrieves all spot ranges for a specific happening.
      parameters:
      - description: Happening ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/uno_domain_model.SpotRange'
            type: array
        "400":
          description: Bad Request
          schema:
            type: type
        "404":
          description: Not Found
          schema:
            type: type
      summary: Get happening spot ranges
      tags:
      - happenings
securityDefinitions:
  BearerAuth:
    description: 'Enter your bearer token in the format: Bearer {token}'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
