basePath: /
definitions:
  adapters_http_routes_api.GroupedRegistration:
    properties:
      max:
        type: integer
      registered:
        type: integer
      waiting:
        type: integer
    type: object
  adapters_http_routes_api.HealthCheckResponse:
    properties:
      status:
        type: string
    type: object
  uno_domain_model.Degree:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  uno_domain_model.Happening:
    properties:
      date:
        type: string
      id:
        type: string
      registration_end:
        type: string
      registration_groups:
        items:
          type: integer
        type: array
      registration_start:
        type: string
      registration_start_groups:
        type: string
      slug:
        type: string
      title:
        type: string
      type:
        type: string
    type: object
  uno_domain_model.Question:
    properties:
      happening_id:
        type: string
      id:
        type: string
      is_sensitive:
        type: boolean
      options:
        items:
          type: integer
        type: array
      required:
        type: boolean
      title:
        type: string
      type:
        type: string
    type: object
  uno_domain_model.Registration:
    properties:
      changed_at:
        type: string
      changed_by:
        type: string
      created_at:
        type: string
      happening_id:
        type: string
      prev_status:
        type: string
      status:
        $ref: '#/definitions/uno_domain_model.RegistrationStatus'
      unregister_reason:
        type: string
      user_id:
        type: string
    type: object
  uno_domain_model.RegistrationStatus:
    enum:
    - registered
    - waiting
    - unregistered
    - pending
    - removed
    type: string
    x-enum-varnames:
    - RegistrationStatusRegistered
    - RegistrationStatusWaitlisted
    - RegistrationStatusUnregistered
    - RegistrationStatusPending
    - RegistrationStatusRemoved
  uno_domain_model.SpotRange:
    properties:
      happening_id:
        type: string
      id:
        type: string
      max_year:
        type: integer
      min_year:
        type: integer
      spots:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: webkom@echo.uib.no
    name: echo Webkom
  description: HTTP REST API for echo Webkom Uno backend
  title: Uno API
  version: "1.0"
paths:
  /:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/adapters_http_routes_api.HealthCheckResponse'
      summary: Get health status
      tags:
      - health
  /degrees:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/uno_domain_model.Degree'
            type: array
      summary: Get degrees
      tags:
      - degrees
    post:
      consumes:
      - application/json
      parameters:
      - description: Degree to create
        in: body
        name: degree
        required: true
        schema:
          $ref: '#/definitions/uno_domain_model.Degree'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/uno_domain_model.Degree'
        "400":
          description: Bad Request
          schema:
            type: type
        "401":
          description: Unauthorized
          schema:
            type: type
      summary: Create degree
      tags:
      - degrees
  /degrees/{id}:
    delete:
      parameters:
      - description: Degree ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            type: type
        "401":
          description: Unauthorized
          schema:
            type: type
      summary: Delete degree
      tags:
      - degrees
    post:
      consumes:
      - application/json
      parameters:
      - description: Degree to update
        in: body
        name: degree
        required: true
        schema:
          $ref: '#/definitions/uno_domain_model.Degree'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/uno_domain_model.Degree'
        "400":
          description: Bad Request
          schema:
            type: type
        "401":
          description: Unauthorized
          schema:
            type: type
      summary: Update degree
      tags:
      - degrees
  /happenings:
    get:
      description: Retrives a list of all happenings and returns them in a JSON array.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/uno_domain_model.Happening'
            type: array
      summary: Get all happenings
      tags:
      - happenings
  /happenings/{id}:
    get:
      description: Retrieves a specific happening by its unique identifier.
      parameters:
      - description: Happening ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/uno_domain_model.Happening'
        "400":
          description: Bad Request
          schema:
            type: type
        "404":
          description: Not Found
          schema:
            type: type
      summary: Get happening by ID
      tags:
      - happenings
  /happenings/{id}/questions:
    get:
      description: Retrieves all questions for a specific happening.
      parameters:
      - description: Happening ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/uno_domain_model.Question'
            type: array
        "400":
          description: Bad Request
          schema:
            type: type
        "404":
          description: Not Found
          schema:
            type: type
      summary: Get happening questions
      tags:
      - happenings
  /happenings/{id}/registrations:
    get:
      description: Retrieves all registrations for a specific happening.
      parameters:
      - description: Happening ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/uno_domain_model.Registration'
            type: array
        "400":
          description: Bad Request
          schema:
            type: type
        "404":
          description: Not Found
          schema:
            type: type
      summary: Get happening registrations
      tags:
      - happenings
  /happenings/{id}/registrations/count:
    get:
      description: Retrieves the count of registrations for a specific happening.
      parameters:
      - description: Happening ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/adapters_http_routes_api.GroupedRegistration'
        "400":
          description: Bad Request
          schema:
            type: type
        "404":
          description: Not Found
          schema:
            type: type
      summary: Get happening registrations count
      tags:
      - happenings
  /happenings/{id}/spot-ranges:
    get:
      description: Retrieves all spot ranges for a specific happening.
      parameters:
      - description: Happening ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/uno_domain_model.SpotRange'
            type: array
        "400":
          description: Bad Request
          schema:
            type: type
        "404":
          description: Not Found
          schema:
            type: type
      summary: Get happening spot ranges
      tags:
      - happenings
securityDefinitions:
  BearerAuth:
    description: 'Enter your bearer token in the format: Bearer {token}'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
